### ISSUE TITLE
Nuorodos veda į atskirus php failus

### ISSUE THREAD

**Issue by ignazas** [AndriusVaiciekauskas/todo_list#1]
![paveikslas](https://user-images.githubusercontent.com/7562987/29268187-663635ca-80f4-11e7-87a2-180c53299bda.png)
Nuorodos veda į atskirus php failus, kai galėtų tiesiog perduoti parametrą per $_GET, ką reikia rodyti.

Tam pasiekt reiktų **all_tasks.php** pervadint tiesiog į **tasks.php**, o failo viduje padaryti tikrinimą ar kas perduodama per pvz $_GET['filter'] ir atitinkamai formuot MySQL užklausą.

**Comment by AndriusVaiciekauskas** [comment]
Done
