### ISSUE TITLE
dbh.php - bereikalingas failas

### ISSUE THREAD

**Issue by ignazas** [AndriusVaiciekauskas/todo_list#3]
![paveikslas](https://user-images.githubusercontent.com/7562987/29270411-4f95495e-80ff-11e7-8a86-fb6a45807fc5.png)

Šitą jau daro DB klasė (komunikuoja su MySQL).
![paveikslas](https://user-images.githubusercontent.com/7562987/29270527-f318e950-80ff-11e7-9f91-cf3dbe73c33f.png)

**Comment by AndriusVaiciekauskas** [comment]
Done
