### ISSUE TITLE
Statusų sąrašas turėtų būti imamas iš atskiros db lantelės o ne hardcoded

### ISSUE THREAD

**Issue by ignazas** [AndriusVaiciekauskas/todo_list#7]
Kad turėti galimybę keisti statusų sąrašą reikia juos imti iš db. tam reikės lentelė su ID, Name, FilterName (sintaksisškai saugus vardas pagal kurį galėtume filtruotis).

**Comment by AndriusVaiciekauskas** [comment]
Done
