### ISSUE TITLE
Iškelti db config duomenis iš db.php  failo

### ISSUE THREAD

**Issue by ignazas** [AndriusVaiciekauskas/todo_list#9]
Tam, kad keli žmonės galėtų naudotis projektu ir Jų nustatymai nebūtų nuolat perrašomi, reikia juos iškelti į atskirą failą, kuris GitHub būtų ignoruojamas ir nesinchronizuojamas. Taip kaskart po "pull" iš github nereikės suvedinėt savo nustatymų.

**Comment by AndriusVaiciekauskas** [comment]
Done
